artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Arnab-Ghosh7/Example-2/raw/refs/heads/main/Walmart_Store_sales.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
  required_columns:
    - Store
    - Date
    - Weekly_Sales
    - Holiday_Flag
    - Temperature
    - Fuel_Price
    - CPI
    - Unemployment


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/Walmart_Store_sales.csv
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  model_name: model.pkl


model_evaluation:
  root_dir: artifacts/model_evaluation
  metric_file_name: artifacts/model_evaluation/metrics.json
